repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: |
          (?x)^(
            dist/|
            apps/frontend/.next/|
            apps/frontend/out/|
            \.history/|
            .*\.lock$|
            .*\.min\.js$
          )