title = "VAH gitleaks config"

[allowlist]
# Ignore env example placeholders, test fixtures, etc.
regexes = [
  'CHANGE_ME_AFTER_FIRST_LOGIN',
  'your_(postmark|gocardless|sumsub|address|companies)_.*_here',
  'postgresql://user:pass@host:port/dbname',
]
paths = [
  'app/env.example',
  'server/env.example',
  'scripts/README*',
]
