name: auth-smoke
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci
      - name: Ensure data dir
        run: mkdir -p data

      - name: Seed DB (tables + admin)
        env:
          SQLITE_PATH: ./data/app.db
        run: node scripts/seed.cjs

      - name: Reset admin password (idempotent)
        env:
          SQLITE_PATH: ./data/app.db
        run: node scripts/reset-password.cjs admin@virtualaddresshub.co.uk Admin123!

      - run: npm run build:backend
      - run: |
          (DEBUG_AUTH=1 DEBUG_DB=1 SQLITE_PATH=./data/app.db node dist/server/index.js &) 
          sleep 3
          BASE=http://localhost:4000 npm run test:smoke
