name: Post-Deploy Smoke
on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: smoke-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      
      - name: Warm up Render service
        run: curl -sS -m 5 --connect-timeout 3 https://vah-api-staging.onrender.com/ || true
      
      - name: Smoke staging (patient)
        env:
          SMOKE_BASE_URL: https://vah-api-staging.onrender.com
          SMOKE_INITIAL_DELAY_SECONDS: 120
          SMOKE_MAX_WAIT_SECONDS: 900
          SMOKE_BACKOFF_MAX_SECONDS: 15
        run: bash apps/backend/scripts/smoke.sh
